# WireGuard VPN ティアダウン Composite Action
#
# WireGuard インターフェースを削除し、peer-issuer API でリースを解放する。
# ジョブの終了時に always() 条件で呼び出すことを想定。
#
# 使用方法:
#   - uses: ./.github/actions/wireguard-teardown
#     if: always()
#     with:
#       lease-id: ${{ steps.wireguard.outputs.lease-id }}

name: 'WireGuard Teardown'
description: 'Teardown WireGuard VPN connection and release lease'

inputs:
  lease-id:
    description: 'Lease ID to release'
    required: true
  peer-issuer-url:
    description: 'peer-issuer API URL'
    required: false
    default: 'https://wg-lease.shinbunbun.com'

runs:
  using: 'composite'
  steps:
    - name: Remove WireGuard interface
      shell: bash
      run: |
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          if ip link show wg-ci &>/dev/null; then
            sudo ip link del wg-ci
            echo "WireGuard interface removed (Linux)"
          else
            echo "WireGuard interface not found, skipping removal"
          fi
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          if [[ -f /etc/wireguard/wg-ci.conf ]]; then
            sudo wg-quick down wg-ci || true
            sudo rm -f /etc/wireguard/wg-ci.conf
            echo "WireGuard interface removed (macOS)"
          else
            echo "WireGuard config not found, skipping removal"
          fi
        fi

    - name: Get GitHub OIDC token
      id: oidc
      shell: bash
      run: |
        if [[ -z "$ACTIONS_ID_TOKEN_REQUEST_TOKEN" ]]; then
          echo "::warning::OIDC token not available for lease release"
          echo "available=false" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        OIDC_TOKEN=$(curl -sS -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=${{ inputs.peer-issuer-url }}" | jq -r '.value')

        if [[ -z "$OIDC_TOKEN" || "$OIDC_TOKEN" == "null" ]]; then
          echo "::warning::Failed to get OIDC token for lease release"
          echo "available=false" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        echo "::add-mask::$OIDC_TOKEN"
        echo "token=$OIDC_TOKEN" >> "$GITHUB_OUTPUT"
        echo "available=true" >> "$GITHUB_OUTPUT"

    - name: Release lease
      shell: bash
      if: steps.oidc.outputs.available == 'true'
      env:
        OIDC_TOKEN: ${{ steps.oidc.outputs.token }}
        LEASE_ID: ${{ inputs.lease-id }}
        PEER_ISSUER_URL: ${{ inputs.peer-issuer-url }}
      run: |
        if [[ -z "$LEASE_ID" ]]; then
          echo "::warning::No lease ID provided, skipping release"
          exit 0
        fi

        RESPONSE=$(curl -sS -w "\n%{http_code}" -X POST "${PEER_ISSUER_URL}/release" \
          -H "Authorization: Bearer $OIDC_TOKEN" \
          -H "Content-Type: application/json" \
          -d "{\"lease_id\": \"$LEASE_ID\"}")

        HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
        BODY=$(echo "$RESPONSE" | sed '$d')

        if [[ "$HTTP_CODE" -ge 200 && "$HTTP_CODE" -lt 300 ]]; then
          echo "Lease released successfully: $LEASE_ID"
        else
          # リリース失敗はワーニングのみ（TTL で自動期限切れするため）
          echo "::warning::Failed to release lease (HTTP $HTTP_CODE): $BODY"
          echo "Lease will expire automatically via TTL"
        fi
