# WireGuard VPN ティアダウン Composite Action
#
# WireGuard インターフェースを削除し、peer-issuer API でリースを解放する。
# ジョブの終了時に always() 条件で呼び出すことを想定。
#
# 使用方法:
#   - uses: ./.github/actions/wireguard-teardown
#     if: always()
#     with:
#       lease-id: ${{ steps.wireguard.outputs.lease-id }}
#       authentik-client-id: ${{ secrets.AUTHENTIK_CLIENT_ID }}

name: 'WireGuard Teardown'
description: 'Teardown WireGuard VPN connection and release lease'

inputs:
  lease-id:
    description: 'Lease ID to release'
    required: true
  peer-issuer-url:
    description: 'peer-issuer API URL'
    required: false
    default: 'https://wg-lease.shinbunbun.com'
  authentik-url:
    description: 'Authentik base URL'
    required: false
    default: 'https://auth.shinbunbun.com'
  authentik-client-id:
    description: 'Authentik provider client ID'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Remove WireGuard interface
      shell: bash
      run: |
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          if ip link show wg-ci &>/dev/null; then
            sudo ip link del wg-ci
            echo "WireGuard interface removed (Linux)"
          else
            echo "WireGuard interface not found, skipping removal"
          fi
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          if [[ -f /etc/wireguard/wg-ci.conf ]]; then
            sudo wg-quick down wg-ci || true
            sudo rm -f /etc/wireguard/wg-ci.conf
            echo "WireGuard interface removed (macOS)"
          else
            echo "WireGuard config not found, skipping removal"
          fi
        fi

    - name: Get GitHub OIDC token and exchange via Authentik
      id: auth
      shell: bash
      env:
        AK_URL: ${{ inputs.authentik-url }}
        AK_CLIENT_ID: ${{ inputs.authentik-client-id }}
      run: |
        if [[ -z "$ACTIONS_ID_TOKEN_REQUEST_TOKEN" ]]; then
          echo "::warning::OIDC token not available for lease release"
          echo "available=false" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        OIDC_TOKEN=$(curl -sS -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=wg-lease" | jq -r '.value')

        if [[ -z "$OIDC_TOKEN" || "$OIDC_TOKEN" == "null" ]]; then
          echo "::warning::Failed to get OIDC token for lease release"
          echo "available=false" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        echo "::add-mask::$OIDC_TOKEN"

        # Authentik でトークン交換
        HTTP_RESPONSE=$(curl -sS -w "\n%{http_code}" -X POST "${AK_URL}/application/o/token/" \
          -H 'Content-Type: application/x-www-form-urlencoded' \
          --data-urlencode grant_type=client_credentials \
          --data-urlencode client_id="$AK_CLIENT_ID" \
          --data-urlencode client_assertion_type='urn:ietf:params:oauth:client-assertion-type:jwt-bearer' \
          --data-urlencode client_assertion="$OIDC_TOKEN")

        HTTP_CODE=$(echo "$HTTP_RESPONSE" | tail -n1)
        RESPONSE=$(echo "$HTTP_RESPONSE" | sed '$d')

        if [[ "$HTTP_CODE" -lt 200 || "$HTTP_CODE" -ge 300 ]]; then
          echo "::warning::Authentik token exchange failed (HTTP $HTTP_CODE) for lease release"
          echo "available=false" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        ACCESS_TOKEN=$(echo "$RESPONSE" | jq -r '.access_token')

        if [[ -z "$ACCESS_TOKEN" || "$ACCESS_TOKEN" == "null" ]]; then
          echo "::warning::Failed to get access token for lease release"
          echo "available=false" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        echo "::add-mask::$ACCESS_TOKEN"
        echo "token=$ACCESS_TOKEN" >> "$GITHUB_OUTPUT"
        echo "available=true" >> "$GITHUB_OUTPUT"

    - name: Release lease
      shell: bash
      if: steps.auth.outputs.available == 'true'
      env:
        ACCESS_TOKEN: ${{ steps.auth.outputs.token }}
        LEASE_ID: ${{ inputs.lease-id }}
        PEER_ISSUER_URL: ${{ inputs.peer-issuer-url }}
      run: |
        if [[ -z "$LEASE_ID" ]]; then
          echo "::warning::No lease ID provided, skipping release"
          exit 0
        fi

        RESPONSE=$(curl -sS -w "\n%{http_code}" -X POST "${PEER_ISSUER_URL}/release" \
          -H "Authorization: Bearer $ACCESS_TOKEN" \
          -H "Content-Type: application/json" \
          -d "{\"lease_id\": \"$LEASE_ID\"}")

        HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
        BODY=$(echo "$RESPONSE" | sed '$d')

        if [[ "$HTTP_CODE" -ge 200 && "$HTTP_CODE" -lt 300 ]]; then
          echo "Lease released successfully: $LEASE_ID"
        else
          # リリース失敗はワーニングのみ（TTL で自動期限切れするため）
          echo "::warning::Failed to release lease (HTTP $HTTP_CODE)"
          echo "Lease will expire automatically via TTL"
        fi
