# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # sops-nixの設定
  sops.defaultSopsFile = ../secrets/hardware-configuration.yaml;
  sops.age.keyFile = "/var/lib/sops-nix/key.txt";

  sops.secrets = {
    "disk_uuids/root".owner = "root";
    "disk_uuids/boot".owner = "root";
    "disk_uuids/k8s".owner = "root";
    "disk_uuids/swap".owner = "root";
  };

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
    "sdhci_pci"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/${builtins.readFile config.sops.secrets."disk_uuids/root".path}";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/${builtins.readFile config.sops.secrets."disk_uuids/boot".path}";
    fsType = "vfat";
  };

  fileSystems."/mnt/k8s" = {
    device = "/dev/disk/by-uuid/${builtins.readFile config.sops.secrets."disk_uuids/k8s".path}";
    fsType = "ext4";
    options = [ "nofail" ];
  };

  fileSystems."/export/k8s" = {
    device = "/mnt/k8s";
    options = [
      "bind"
      "nofail"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/${builtins.readFile config.sops.secrets."disk_uuids/swap".path}"; }
  ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # high-resolution display
  #hardware.video.hidpi.enable = lib.mkDefault true;
}
