# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
    "sdhci_pci"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/4f041679-dbeb-4c7d-a371-39f44857d619";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/3734-ECC0";
    fsType = "vfat";
  };

  fileSystems."/mnt/k8s" = {
    device = "/dev/disk/by-uuid/dc37e1f6-c488-4491-b524-96fc14e27a92";
    fsType = "ext4";
    options = [ "nofail" ];
  };

  fileSystems."/export/k8s" = {
    device = "/mnt/k8s";
    options = [
      "bind"
      "nofail"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/42a8faf1-0f52-476e-a6d9-1fd777514493"; }
  ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # high-resolution display
  #hardware.video.hidpi.enable = lib.mkDefault true;
}
