name: Auto Update Flakes (PR Mode)

# PAT_TOKEN を事前にリポジトリの Secrets に登録しておいてください
on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

permissions:
  contents: write # リポジトリの読み書き
  pull-requests: write # PR の作成・更新

jobs:
  update-flakes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Install Nix
        uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Update flake
        run: |
          nix flake update

      - name: Check for changes
        id: changes
        run: |
          if ! git diff --exit-code; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request for flake.lock update
        if: steps.changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          commit-message: "Auto-update flake.lock"
          title: "Auto-update flake.lock"
          body: |
            This PR updates flake.lock with the latest input updates via `nix flake update`.

            Please review and merge if everything looks OK.
          branch: auto/update-flake-lock
          base: main
          draft: false
