discord:
    webhook_url: ENC[AES256_GCM,data:+ZOS75zelJrthZCfJWmfGt29xgW2ls3CpsCGFcG3V2h3rcbtFl3htIeBxyQJnZrKVEkQl5wrXam4DbcdGKRDS3tV4aUKhhvyhSgnGY3i4wmWHpnpgpV5mfIbMNYXP01/apcrePnxbSbUSCFuiSqSGrkUUZUkfNuYvQ==,iv:+JWQgq5vbsM2itYoiFSM79UxTCHYNazeUSFztM09TG0=,tag:mYzcszpdKHgq+Qn/ItVCiw==,type:str]
    user_id: ENC[AES256_GCM,data:sO2e/K7H5w/OrMJpSC68Dmkg,iv:+UgQPdcGJAtw6vaaBAzQ+LnFTfJw7/fSSHW3vB6ukGI=,tag:1jv0ldD2wh11nbBRKi+Lug==,type:str]
sops:
    age:
        - recipient: age1p057v4es63p6fef8usy67tkza7dj4xg326w5gm3c7rdthcd3xqlqps38z9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzQlZnSERIU0t1WHZxYzV0
            UkNQbENxQThDVy9scnhsdGRZSEZ6SmFNWlJBCjBUSkVYdk1GYWxHMXBxd3ZpWlRy
            QXFMTGRqUzFzYkVsMEhVeVZFc2x1ZVkKLS0tIFA1NC9CUUxJbnZWc1BxdmVHTlRh
            eUNoU1VjUUZ0SkNVQ0FHZTNBcmhFdEUKt2nUIP5bSXKZtlp9LxsfP3/vnpqLpJg0
            x2CGji5pLOekSOXsBQZPGpEszRVVoWUnlpvotcYb9aXoAb2rvg410Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tuyn9u7qca3mpk082a94mnwpwgue7wlux2c7mruyxg7fz9y45qrqnqw3yx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRnR4MjFKNDgyNWpGdm5S
            RjVqK2ZYZThuaUV1d09HYkZaMDNPVE9oaFNNCmg0aWJEUlF5TW9VOGF1N2cvRXoz
            OHVURUZSakd4MFl1L0VERmRqanlOS28KLS0tIFM1MG9LR002UEttME5sVUE2SU5X
            RGwvWko0SkZFb1R1WVIrVVgyWjFHU0EKbv/sPOpw0WokXtvpjRMnpVUnJi8vEB5p
            PckE8ocFdPHO/ZCiyPpscL2irwrM71onsdBlXvzMrtQ/P6cvdzFamg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age124zeln7fujjzwpaeq2lmg00r93t4kp7tea684yr85prk0zh9jvfqj247af
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmS2kzN3dsN1FMUG12dUpm
            cW5zd29wc0RqWmxGNFUzUkIrcHYwY0lnNTJVCnAwb2tseHdzaXFnWlNjZVZ0ZFl3
            dHlqK2J5RXhPVm9IRmNRRndnZkJMaDQKLS0tIFVQSFRYWEMrSittdk12c0YzcHQz
            djhFbGo0N3F3YkJ5c1NxWW5oNHBQUWMKOsZ9H3hWkcHnZIems2r8jWWDsCITbYqf
            frcRodtupuTvPmOGeRXqytlg5HGoHnG2ah9iMeP7takEljONVvsXHA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1n9tqc8fc5cecey0ca4l2kj74arzl96rnj9kqu02x7amsw2g58erqdcxfpd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3R09KWWRRY2FHUWVZNzRI
            cWJJSmREL3hzVDErRVpoZDN0NXpuNzR0eWlvCi9ZbTJIZnBudU9MeEpUOHZyVVor
            VGsvSDBhOUxvZnRYVlZocWxIeS9xUUkKLS0tIExjUzBPVFYySWRyWVI5MU14VWhr
            RWlvVWJTY3VVZHVMU0UzNXh3R1ZXK28KtzYtQz52EZmF4tpRkYyJowZECv5Zblnp
            I81US8eJ24LfXgDt3EiUQ/tjByq78ZQ/bz06O3/ek3WpS4gb/0PxHQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1sad5k5y967aeq82y6nk5yuzc6cf2fpxxs3y7juf6n3jrcryutgpqwqtt79
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTYlhwbnphWCtSK2lrdWdw
            VjJzYzN3YXlFUkhMNWlibVpzaW4zWUJ2SVJVCjM0MTRKVGxURWZRN1FjWEJUY3RJ
            NThjZlBpS3RWanJYeHRqcXZ1Q1ZVSFkKLS0tIDB3V0dGRmk5T3d1RSt4UVMyUFVC
            TDh5QkNLS09ybzBDWFhIMnlhOVFXTE0K3i6ju/7gEVNBbWDptxaIvqhpPR8s2uVH
            zD4RLCBeUNde0HFOlb+hg7jogBL6mUVqu8UHf3nyG3mUIHo7PDtOxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-27T05:47:55Z"
    mac: ENC[AES256_GCM,data:sehcsHNqizf/iNlJrcbNPH4rp4sY/5arb4ySwUK6mPCXm7Woqi7a1Cva4LyorCqrHWGxyLmKj9ZqetjNs0Kb7W4fA3lpQMMMMy45ox+alvyyAzskDg+hz0zSx3wSZHTdShxqiwdbVUPW3C7sk0p/bG4OaxnlG8Fv/SJyWpA4W9E=,iv:5Bh4f3nWeWF6rl7kSiTZvlvaqiokTdO2EiBoHiD+Q0w=,tag:8phwxN3fSek19Jvc9u31bQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
