disk_uuids:
    root: ENC[AES256_GCM,data:0ITowpGHrLCFdZ3g9u16RW3TA4zAHwF4EcQ+9+ZDcL8BQGlo,iv:4q2H6M7OYlpJuXBBvRjqTxQ4jZxZtRkdNMzr0tkMww4=,tag:lD7ueNZ25VEvJtdMr3366Q==,type:str]
    boot: ENC[AES256_GCM,data:24WydvFZUoPL,iv:pOx4d1QZ/sUt5c+IOt32pYYgALz32G0X96nnT26kr7U=,tag:Msx4rcC2wOreYIm4MkGzHw==,type:str]
    k8s: ENC[AES256_GCM,data:bB89oFwSHgjkLs73tVU+6mw6XdnSuMeZ7qfTA54w0eq6YXSG,iv:RaBNjptFcYEpu53ipZJCrG+UD/cZlkcIy41K4gvAJq4=,tag:ty7Zd8CMXknBHA5J4rORYw==,type:str]
    swap: ENC[AES256_GCM,data:cEsiM0RrLL2Ap9ZaTD/q3SM9uYIfRpd7MiyHbP6s2g2viMBc,iv:0KWn9TRhBJER3dKmo2UZWkdPIwyPKvtF5gTotFvHbco=,tag:cX+KxKOcaEB/5wuvK7zqxQ==,type:str]
sops:
    age:
        - recipient: age1p057v4es63p6fef8usy67tkza7dj4xg326w5gm3c7rdthcd3xqlqps38z9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArWnNzVVdWcGgrUjFVTHZ0
            eFVWbjF0ZUdtZTB4MjkzSlN0N0NHZUdpa21nCmRUTjRHTnpoc2ovSEhHTlB6Z2Qw
            SDN4cE9ndUEwOGd2OUc0aGNlQzJNMHcKLS0tIFlUK1RXVzdja3pROWFMeUUxR3Iy
            V0NlNDAxV29tbTdld3dDN01FY2VXOFUKjbEQGXktSCNl5+Vi5vyICdVcoI1XS1Dl
            IgK+ZbaJOONaqc95n7TR/ql/05OZI/jVx7rhjde5kNsoZneoRr4Ofw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tuyn9u7qca3mpk082a94mnwpwgue7wlux2c7mruyxg7fz9y45qrqnqw3yx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKL1BSaTIvbEtzbytlcWFl
            a3NLbm9weWZkbWxJdVY2MmVVQjhPSTk5WXpjCmEzcFVaN0tneUFkckwrTmNBYzQw
            YXJkbWRvM3dhSGhTNGVEN0taaWV2cjQKLS0tIFpoU09wbllVSmg3ZTI0Z0I4T0JQ
            WGNVV2pYM1ZmYjBUUStGZWtxWWdKNkUK8HRnWlIx1JdUFmg2GYi9/bL/7+lypzFN
            +NhjU5WZjLyluCyxJD1rJHrV76RSAAbvttTZVNVOGeT12BNsjMUCDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-18T02:49:50Z"
    mac: ENC[AES256_GCM,data:HeqvHjhBg50pKjtUMYVK8UiJeuyRl91QdxPnFTyCf3H1sxDFKXrT7M9ENwvfxIYJsCcEvbhm/lZEbHzWwvZuOrS03oYJ9EE4r2UoZfPXWwCxJQ37jTUiJ0fP+H5GkxPF9MfbfaUu/ZpZX8RKInTnSf7R2OQd/5qnrnp5E+5ypc0=,iv:dSWwj2lXYDsyPO92bQspOaDCMGvJuvIfPb6ZJKrGcBY=,tag:YBrNFuAM1URmoanwo/4w/Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.1
