disk_uuids:
    root: ENC[AES256_GCM,data:0ITowpGHrLCFdZ3g9u16RW3TA4zAHwF4EcQ+9+ZDcL8BQGlo,iv:4q2H6M7OYlpJuXBBvRjqTxQ4jZxZtRkdNMzr0tkMww4=,tag:lD7ueNZ25VEvJtdMr3366Q==,type:str]
    boot: ENC[AES256_GCM,data:24WydvFZUoPL,iv:pOx4d1QZ/sUt5c+IOt32pYYgALz32G0X96nnT26kr7U=,tag:Msx4rcC2wOreYIm4MkGzHw==,type:str]
    k8s: ENC[AES256_GCM,data:bB89oFwSHgjkLs73tVU+6mw6XdnSuMeZ7qfTA54w0eq6YXSG,iv:RaBNjptFcYEpu53ipZJCrG+UD/cZlkcIy41K4gvAJq4=,tag:ty7Zd8CMXknBHA5J4rORYw==,type:str]
    swap: ENC[AES256_GCM,data:cEsiM0RrLL2Ap9ZaTD/q3SM9uYIfRpd7MiyHbP6s2g2viMBc,iv:0KWn9TRhBJER3dKmo2UZWkdPIwyPKvtF5gTotFvHbco=,tag:cX+KxKOcaEB/5wuvK7zqxQ==,type:str]
sops:
    age:
        - recipient: age1p057v4es63p6fef8usy67tkza7dj4xg326w5gm3c7rdthcd3xqlqps38z9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1UHFYTmRqYSttcE1BcTRx
            MFoySit3WnY4U25lK1NQdVRFRncrVHFyL1hrCmxnZC9Sa3NOWWFLZVV2UGVUQnY4
            RUw3Skk2c01oVEFmWTlRandtRHBUV1EKLS0tIHA1cWNBVmY3MHRRajhkclVhSEJZ
            Um1yR216U1JabDF2YWl5bmIxd2I0SUUKq//PDz7vKat49dD3inqlH6oK/v8K0wcw
            YD7radZRnbStHOADCiQJ0/xqRyV/AOYwkhQeS8oRDCFkxJ8Yefkybw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-18T02:49:50Z"
    mac: ENC[AES256_GCM,data:HeqvHjhBg50pKjtUMYVK8UiJeuyRl91QdxPnFTyCf3H1sxDFKXrT7M9ENwvfxIYJsCcEvbhm/lZEbHzWwvZuOrS03oYJ9EE4r2UoZfPXWwCxJQ37jTUiJ0fP+H5GkxPF9MfbfaUu/ZpZX8RKInTnSf7R2OQd/5qnrnp5E+5ypc0=,iv:dSWwj2lXYDsyPO92bQspOaDCMGvJuvIfPb6ZJKrGcBY=,tag:YBrNFuAM1URmoanwo/4w/Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.1
